package com.keygen.key.model;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;
import java.util.Objects;
import java.util.UUID;


@Entity
public class Key {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    private String key = "autogenerated key id = " ;

    private Date creationDate;

    private Date expirationDate;

    private int durationn;

    Key(UUID id){
        this.id = id;
    }

    public String getKey() {
        //TODO: find and efficient way to decrypt the key
        return key;
    }

    private void setKey() {
        //TODO: Find an efficient way to generate and encrypt the key
        String key = "autogenerated key id = " + this.getId().toString();
        this.key = key.toString();
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public Key setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
        return this;
    }

    public Date getExpireDate() {
        return expirationDate;
    }

    public Key setExpirationDate(Date expireDate) {
        this.expirationDate = expireDate;
        return this;
    }

    public int getDurationn() {
        return durationn;
    }

    public void setDurationn(int durationn) {
        this.durationn = durationn;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return "Key{" +
                "id=" + id +
                ", key='" + key + '\'' +
                ", creationDate=" + creationDate +
                ", expirationDate=" + expirationDate +
                ", durationn=" + durationn +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Key)) return false;
        Key key1 = (Key) o;
        return durationn == key1.durationn &&
                Objects.equals(id, key1.id) &&
                Objects.equals(key, key1.key) &&
                Objects.equals(creationDate, key1.creationDate) &&
                Objects.equals(expirationDate, key1.expirationDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, key, creationDate, expirationDate, durationn);
    }
}
